# OIDC credentials (auto-generated by Cloudflare)
output "access_client_id" {
  description = "OIDC client ID — set as ACCESS_CLIENT_ID Worker secret"
  value       = cloudflare_zero_trust_access_application.mcp.saas_app[0].client_id
  sensitive   = true
}

output "access_client_secret" {
  description = "OIDC client secret — set as ACCESS_CLIENT_SECRET Worker secret"
  value       = cloudflare_zero_trust_access_application.mcp.saas_app[0].client_secret
  sensitive   = true
}

# OIDC URLs (derived from team name + client ID)
locals {
  client_id = cloudflare_zero_trust_access_application.mcp.saas_app[0].client_id
  base_url  = "https://${var.cloudflare_team_name}.cloudflareaccess.com/cdn-cgi/access/sso/oidc/${local.client_id}"
}

output "access_token_url" {
  description = "OIDC token URL — set as ACCESS_TOKEN_URL Worker secret"
  value       = "${local.base_url}/token"
}

output "access_authorization_url" {
  description = "OIDC authorization URL — set as ACCESS_AUTHORIZATION_URL Worker secret"
  value       = "${local.base_url}/authorization"
}

output "access_jwks_url" {
  description = "JWKS URL — set as ACCESS_JWKS_URL Worker secret"
  value       = "${local.base_url}/jwks"
}

# Summary
output "worker_secrets_summary" {
  description = "All Worker secrets needed for OAuth — run 'terraform output -json worker_secrets_summary' to get values"
  value = {
    ACCESS_CLIENT_ID         = cloudflare_zero_trust_access_application.mcp.saas_app[0].client_id
    ACCESS_CLIENT_SECRET     = cloudflare_zero_trust_access_application.mcp.saas_app[0].client_secret
    ACCESS_TOKEN_URL         = "${local.base_url}/token"
    ACCESS_AUTHORIZATION_URL = "${local.base_url}/authorization"
    ACCESS_JWKS_URL          = "${local.base_url}/jwks"
  }
  sensitive = true
}
